<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.63.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.12" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.23.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.23.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DevBrain.Core.Tests" />
    <InternalsVisibleTo Include="DevBrain.Server" />
    <InternalsVisibleTo Include="DevBrain.Server.Tests" />
  </ItemGroup>

</Project>
